### ISSUE TITLE
Build docker image

### ISSUE THREAD

**Issue by pawelszczerbicki** [gavacho/ecs-deploy#10]
Hello,
Do you support any tool for building and pushing docker images to ecr ? Your plugin assumes that image is currently in ECR, am I right ?

**Comment by gavacho** [comment]
The only tool i use for building & pushing docker images is `docker build` and `docker push`.  This script "updates" (by creating a new version) of an existing task definition and allows you to specify whatever image you want.  The image value may be something like `docker.io/myorg/myproject:mytag` but I think it can also target something other than docker.io (docker hub).

Sorry I don't have the exact answer you're looking for.

**Comment by pawelszczerbicki** [comment]
Sorry mi mistake :) Just set ENV var
