### ISSUE TITLE
Multiple ECS container targets

### ISSUE THREAD

**Issue by skellertor** [gavacho/ecs-deploy#5]
Thanks for creating this! In my use case I have my services running across a few ec2 instances.  How do I specify multiple containers for the `CONTAINER` environment variable? Thanks

**Comment by gavacho** [comment]
There currently isn't support for multiple containers.

A possible workaround could be to run ecs-deploy once for every container.

**Comment by skellertor** [comment]
Are you accepting pull requests?  What would you think of making the environment variable `CONTAINER` optional?  If it is there, update that container, if it is not there, updated all containers.

It looks like you have access too them in the `nextTask()` function.

**Comment by gavacho** [comment]
Yes pull requests are very welcome
